### ISSUE TITLE
Tooltips are often unhelpful because of size or placement

### ISSUE THREAD

**Issue by kaiyoma** [btd/rollup-plugin-visualizer#167] opened 2023-09-28 15:24 UTC
(initially filed this bug here: https://github.com/KusStar/vite-bundle-visualizer/issues/9)

I find that the tooltips are often too big or rendered in the wrong direction, causing the most important information (the sizes) to be unavailable. Some examples:

Hovering over an entry at the top of the screen causes the tooltip to be rendered upwards for some reason:

![image](https://github.com/KusStar/vite-bundle-visualizer/assets/10719780/1edaaddc-40ed-470c-9e75-dd737ef01189)

Long lists of files are not truncated, causing the size information to be unavailable:

![image](https://github.com/KusStar/vite-bundle-visualizer/assets/10719780/21f8904d-44a3-4bc9-9457-349968ebb314)

**Comment by btd** [comment] 2023-11-24 14:50
Yep, this is known problem. I do not have good solution for this.

**Comment by btd** [comment] 2023-11-24 15:00
Looks like duplicate of https://github.com/btd/rollup-plugin-visualizer/issues/154. I will close this one to track it in one place

**Closed by btd** 2023-11-24 15:00 UTC

**Comment by btd** [comment] 2023-12-09 16:08
Aggregated issue https://github.com/btd/rollup-plugin-visualizer/issues/183
