### ISSUE TITLE
The data size in report not matched with actual output

### ISSUE THREAD

**Issue by scott-avery** [btd/rollup-plugin-visualizer#130] opened 2022-09-26 10:13 UTC
- [x] Provide your rollup config (this is most important, because some plugins changes paths to files)

inherited from vite internal, no manual changes.

- [x] Provide your node and dependencies versions

```
node v16.17
vite v3.1.3
```

- [x] Your OS type and version

macOS Monterey 12.6

- [x] Screenshot of problem
<img width="753" alt="image" src="https://user-images.githubusercontent.com/105617446/192250714-e7676c73-7c8f-46b6-927b-60c7e1bb7dac.png">
<img width="1720" alt="image" src="https://user-images.githubusercontent.com/105617446/192250874-5fe4224b-66cf-4e19-bc30-034f22d78cbb.png">

**Comment by btd** [comment] 2022-09-26 10:19
Seriously, i even pinned issue to make visible. How can i make people to look/search first?

Duplicate of https://github.com/btd/rollup-plugin-visualizer/issues/96

Reopen if it is not the case

**Closed by btd** 2022-09-26 10:19 UTC

**Comment by scott-avery** [comment] 2022-09-27 02:02
Thank you @btd. My bad, I only searched for vite and no similar result found.

BTW, mentioning it in readme would be more ideal and visible to users.

**Comment by btd** [comment] 2022-09-30 14:46
Sorry @scott-avery but nobody really read readme (sorry if you are exception). I even one time had issue, that somebody could not find options in readme, until i gave direct link with hash. But i will think about adding to readme, i think if at least some part of users will find it there it will reduce number of issues in general
